
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  springboot-app:
    build: .
    container_name: springboot-container
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  sql_data: