spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=cvdb;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong@Pass123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect